services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    container_name: ephemera-postgres
    environment:
      POSTGRES_DB: ephemera
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 3

  mailpit:
    image: axllent/mailpit:latest
    container_name: ephemera-mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ephemera-backend
    restart: unless-stopped
    env_file:
      - .env.local
    depends_on:
        postgres:
          condition: service_healthy
        mailpit:
           condition: service_started
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    container_name: ephemera-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
    postgres_data:
    mailpit-data:
    redis_data: